In [2]:
import numpy as np

### array의 생성

In [3]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array)

numpy.ndarray

In [5]:
test_array = np.array([1, 4, 5, "8"], np.float32)   # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.], dtype=float32)

In [6]:
type(test_array[3])     # Float Type으로 자동 형변환 실시

numpy.float32

In [7]:
test_array.dtype

dtype('float32')

In [8]:
np.array([[1, 4, 5, "8"]], np.float32).shape

(1, 4)

In [9]:
test_array.shape    # Array(배열)의 Shape을 반환함.

(4,)

### array shape

In [10]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [11]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [15]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 3, 4]],
          [[1, 5, 3, 8], [1, 2, 3, 4], [1, 4, 6, 2]]]
np.array(tensor, int).shape

(4, 3, 4)

In [16]:
np.array(tensor, int).ndim 

3

In [17]:
np.array(tensor, int).size

48

### numpy dtype

In [20]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)
a.dtype

dtype('int32')

In [25]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [26]:
np.array([[1, 2, 3], [3.5, "5", "6"]], dtype=np.float32).nbytes

24

In [28]:
np.array([[1, 2, 3], [4.6, '5', '6']], dtype=np.int8).nbytes

6

In [29]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float64).nbytes

48