In [1]:
import numpy as np

### reshape

In [2]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [5]:
test = np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [6]:
test.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [7]:
np.array(test_matrix).reshape(2, 4).shape

(2, 4)

In [8]:
np.array(test_matrix).reshape(2, -1).shape

(2, 4)

In [9]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [10]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

### flat or flatten()

In [18]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
print(np.array(test_matrix).flatten())

[1 2 3 4 1 2 5 8 1 2 3 4 1 2 5 8]
