In [19]:
import numpy as np

In [20]:
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
test_example[0, 0]

1

In [22]:
test_example[0][0]

1

In [23]:
test_example[0, 0] = 10 
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [24]:
test_example[0][0] = 5
test_example[0, 0]

5

### slicing

In [25]:
test_example = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]], int)
test_example[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
print(test_example[:, 1:3])
print(test_example[1, :2])

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[5 6]


In [27]:
test_example = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_example[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [28]:
test_example[1, 1:3]

array([7, 8])

In [33]:
test_example[1:2]

array([[ 6,  7,  8,  9, 10]])

In [30]:
a = np.arange(100).reshape(10, 10)
a[:, -1].reshape(-1, 1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])