In [17]:
import numpy as np

### all & any

In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [20]:
np.any(a>5), np.any(a<0)

(True, False)

In [21]:
np.all(a>5), np.all(a<10)

(False, True)

### comparision operation

In [22]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [23]:
test_a == test_b

array([False, False, False])

In [24]:
(test_a > test_b).any()

True

In [25]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [26]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [27]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [28]:
a

array([1., 3., 0.])

In [29]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [30]:
np.where(a > 0)

(array([0, 1], dtype=int64),)

In [31]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [33]:
a = np.array([1, np.NAN, np.inf], float)
np.isnan(a)

array([False,  True, False])

### argmax & argmin

In [35]:
a = np.array([1,2,4,5,8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

In [36]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))